### ISSUE TITLE
设置圆角之后控件就不显示了

### ISSUE THREAD

**Issue by wangjing71** [Arcns/arc-fast#1]
<com.arc.fast.view.rounded.RoundedTextView
                android:id="@+id/dialog_btn_left"
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_gravity="center"
                android:layout_marginRight="10dp"
                android:layout_weight="1"
                android:gravity="center"
                android:singleLine="true"
                android:text="不同意"
                android:textColor="#3390e8"
                android:textSize="@dimen/sp_17"
                android:visibility="visible"
                app:rounded_background_color="#E9E9E9"
                app:rounded_radius_top_left="10dp" />

没加app:rounded_radius_top_left="10dp" 就能显示

**Comment by wangjing71** [comment]
android:singleLine="true"
这个去掉了 就能显示了

**Comment by Arcns** [comment]
@wangjing71 
 @抱歉，最近工作很忙，回复慢了
在TextView中，android:singleLine="true"会与canvas.draw圆角产生冲突，请改为使用
```
android:lines="1"
```
来限制行数
