### ISSUE TITLE
挺好用的 能少写很多shape

### ISSUE THREAD

**Issue by wangjing71** [Arcns/arc-fast#2]
希望FastTextView能增加自定义文字粗细的属性
<attr name="fastTextView_textBold" format="float" />
app:fastTextView_textBold="1.0"
app:fastTextView_textBold="1.5"
app:fastTextView_textBold="1.8"
app:fastTextView_textBold="2.0"
....

这是我自己修改的。。

**Comment by Arcns** [comment]
@wangjing71 谢谢，这个建议很好，新版本已加上：
fastTextView_textBoldFontWeight，设置粗体大小，优先级高于fastTextView_textMediumBold
